{
  "expo": {
    "name": "Nexus App",
    "slug": "nexus-app",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#040301"
    },
    "android": {
      "package": "com.empresa.app",
      "versionCode": 1,
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#040301"
      },
      "permissions": [
        "INTERNET",
        "CAMERA",
        "ACCESS_FINE_LOCATION",
        "VIBRATE"
      ]
    },
    "plugins": [
      "expo-camera",
      "expo-location"
    ],
    "extra": {
      "eas": {
        "projectId": ""
      }
    }
  }
}
